apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.user1: apiKey, login
  accounts.kedar: apiKey, login